name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
  TARGET_HOST: ${{ secrets.TARGET_HOST }}
  TARGET_USER: ${{ secrets.TARGET_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      #########################################################
      # DockerHub Login
      #########################################################

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #########################################################
      # Build Images
      #########################################################

      - name: Build Backend Image
        run: |
          docker build \
            -f backend/Dockerfile \
            -t ${DOCKER_USER_NAME}/${IMAGE_NAME}-backend:${IMAGE_TAG} .

      - name: Build Frontend Image
        run: |
          docker build \
            -f frontend/Dockerfile \
            -t ${DOCKER_USER_NAME}/${IMAGE_NAME}-frontend:${IMAGE_TAG} .

      #########################################################
      # Push Images
      #########################################################

      - name: Push Backend
        run: |
          docker push ${DOCKER_USER_NAME}/${IMAGE_NAME}-backend:${IMAGE_TAG}

      - name: Push Frontend
        run: |
          docker push ${DOCKER_USER_NAME}/${IMAGE_NAME}-frontend:${IMAGE_TAG}

      #########################################################
      # SSH Configuration
      #########################################################

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H $TARGET_HOST >> ~/.ssh/known_hosts

      #########################################################
      # Create .env
      #########################################################

      - name: Create Environment File
        run: |
          printf "%s" "${{ secrets.ENV_FILE }}" > .env

      #########################################################
      # Deploy
      #########################################################

      - name: Deploy Application
        run: |

          APP_DIR="assignment"

          ssh ${TARGET_USER}@${TARGET_HOST} "

          if [ ! -d \$HOME/${APP_DIR} ]; then
              git clone https://github.com/${{ github.repository }} \$HOME/${APP_DIR}
          else
              cd \$HOME/${APP_DIR}
              git pull origin main
          fi
          "

          scp .env ${TARGET_USER}@${TARGET_HOST}:~/assignment/.env

          ssh ${TARGET_USER}@${TARGET_HOST} "

          set -e

          cd ~/assignment

          chmod +x deployment/scripts/docker-install.sh

          ./deployment/scripts/docker-install.sh

          docker login \
            -u '${DOCKER_USER_NAME}' \
            -p '${DOCKER_PASSWORD}'

          docker compose \
            -f deployment/docker/docker-compose.yml \
            pull

          docker compose \
            -f deployment/docker/docker-compose.yml \
            up -d

          docker image prune -af

          docker ps

          "
